### ISSUE TITLE
Sequence length parameter has no effect on data loader for MAVE data

### ISSUE THREAD

**Issue by Al-Murphy** [bowang-lab/genomic-FM#55]
There appears to be an issue with the dataloader functionality where it seems to ignore the `Seq_length` parameter and just return a fixed length. See below for examples from the MAVE data.

```
from src.dataloader.data_wrapper import (
    MAVEDataWrapper
)

NUM_RECORDS = 100
ALL_RECORDS = False
SEQ_LEN = 2_000
#SEQ_LEN = 100

# Load MAVE data
data_loader = MAVEDataWrapper(num_records=NUM_RECORDS, all_records=ALL_RECORDS)
data = data_loader.get_data(Seq_length=SEQ_LEN)

print(len(data[0][0][0]))
#477 - no matter the value of SEQ_LEN
```

**Comment by vsubasri** [comment]
Hi Alan, It appears there is an non-numeric character ("_") in your SEQ_LEN variable "2_000" please update to 2000 and try again.

**Comment by vsubasri** [comment]
Hi Alan, It appears there is an non-numeric character ("_") in your SEQ_LEN variable "2_000" please update to 2000 and try again.

**Comment by Al-Murphy** [comment]
Hey! 

Python usually allows for `_` to denote ',' in numbers: 2,000 -> 2_000.

Using `SEQ_LEN = 2000` has the same issue

**Comment by Al-Murphy** [comment]
I actually personally think it would be better not to try and map it to some genomic sequence - the fact that it is completely generated DNA is useful. However, I think adding functionality to pad with 'N's or shorten the sequence based on the inputted SEQ_LEN would be useful so that it fits with models' parameters.

Anyway just an idea, thanks for the explanation Valli!

Alan.
